### ISSUE TITLE
Standardizing Code Style

### ISSUE THREAD

**Issue by isidentical** [coogger/coogger#103]
With a series of tools, codebase should formatted with-in a standard. I am proposing `black` and `isort` for this mission.

**Comment by hakancelik96** [comment]
Good choice and issue, It will be good to write them in the readme and contributing.md files. You can get this issue if you have time.

- [CONTRIBUTING.md](https://github.com/coogger/coogger/blob/master/CONTRIBUTING.md)
- [README.md](https://github.com/coogger/coogger/blob/master/README.md)
- [black](https://github.com/psf/black)
- [isort](https://github.com/timothycrosley/isort)
--------
Do not forget to specify these using [shields.io](https://shields.io/)
