### ISSUE TITLE
Empty page on search results.

### ISSUE THREAD

**Issue by aligoren** [coogger/coogger#114]
**Describe the bug**
Hi. When I trying to search for something result page shows an empty page.

For example; [https://www.coogger.com/search/?query=empty](https://www.coogger.com/search/?query=empty)

**To Reproduce**
1. Go to 'top of the coogger'
2. Click on 'search input'
3. Type something like 'empty'
3. Hit enter
4. See the empty page

**Expected behavior**

If there is nothing, users should see 404 or similar pages.

**Additional context**

The result page could be much better if it would be like that;

```
Search Results for YOUR_KEYWORD
Apologies, but no results were found for the requested archive. 
Perhaps searching will help find a related post.
```

**Comment by hakancelik96** [comment]
That is a good point, you can take this assignment if you want, In addition, I can help you with this issue.
