### ISSUE TITLE
Auth Sisteminin Firebase'e geçirilmesi

### ISSUE THREAD

**Issue by BTaskaya** [coogger/coogger#22]
Djangonun kendi Auth modeli yerine daha yenilikçi çözümler kullanılmalı bence.

Google Firebase bu iş için biçilmiş kaftan. Firebase ile beraber sadece mail değil sosyal medya servisleri ile de kayıt alabiliyorsun ki çoğu kullanıcı bunu tercih eder.
![image](https://user-images.githubusercontent.com/25110697/34320571-63744eae-e80e-11e7-9824-d615b040a484.png)

Ayrıca Firebase entegresi kolay olan sayılı servislerden biridir. Google sağolsun.

Çalışma prensibi:
![image](https://user-images.githubusercontent.com/25110697/34320589-b5e0ae30-e80e-11e7-9eab-c9208c39f1a5.png)

---

https://firebase.google.com/docs/auth/web/start - Web İçin

Bu videoyu kesinlikle izle 😄 
https://www.youtube.com/embed/8sGY55yxicA?list=PLl-K7zZEsYLmOF_07IayrTntevxtbUxDL

**Comment by hakancelik96** [comment]
Gayet güzel en yakın zamanda eklenir umarım 😅 öğrenir eklerim yada hayrına biri eklesin 😀

**Comment by BTaskaya** [comment]
Keşke şu django skillerimi konuşturacak vaktim olsa :D

**Comment by hakancelik96** [comment]
https://firebase.google.com/ mobil uygulama diyor bu benmi yanlış anladım

**Comment by BTaskaya** [comment]
Web için de var Mobil için de Desktop için de.

16 Oca 2018 14:19 tarihinde "Hakan Çelik" <notifications@github.com> yazdı:

https://firebase.google.com/ mobil uygulama diyor bu benmi yanlış anladım

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakancelik96/coogger/issues/22#issuecomment-357930286>,
or mute the thread

**Comment by hakancelik96** [comment]
sonradan anlayınca yorumu silmiştim 👍

**Comment by BTaskaya** [comment]
Mail üzerinden cevap yazıyorum, maillerde silindiği gözükmüyor, kusura
bakma.

16 Oca 2018 14:55 tarihinde "Hakan Çelik" <notifications@github.com> yazdı:

sonradan anlayınca yorumu silmiştim 👍

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hakancelik96/coogger/issues/22#issuecomment-357938342>,
or mute the thread
