### ISSUE TITLE
Need logo

### ISSUE THREAD

**Issue by hakancelik96** [coogger/coogger#26]

**Comment by linadesteem** [comment]
Hi, what do you think of this? 
![image](https://user-images.githubusercontent.com/35618068/38006161-27d76476-326e-11e8-8528-004ef945c482.png)

**Comment by linadesteem** [comment]
Oh no
I missed one letter G in every version. Please let me know if you like any of those logomark. Then i'll edit the logotype :)

**Comment by hakancelik96** [comment]
doesn't matter ,I wrote comment check steemit

**Comment by hakancelik96** [comment]
I copied
[-]hakancelik (56)  ·  3 minutes ago
Yeah I see on github, I will open a logo task requests in utopian-io, when I do this, you can redesign it because I want to see it in other people, but i can say that,I want to see in my logo that coogger's green and resembling information sharing like light symbol or etc.

**Comment by linadesteem** [comment]
okay sir i will make a post in utopian when you make task request in utopian.
meanwhile i've design another logo sir, maybe you can give me feedback

![image](https://user-images.githubusercontent.com/35618068/38089155-a6f56d78-3388-11e8-981d-3e1d952fdb0c.png)

![image](https://user-images.githubusercontent.com/35618068/38089160-abcde640-3388-11e8-9fa0-396b65203ebb.png)

colour green smae with green in your website

**Comment by hakancelik96** [comment]
I like it more, it's nice and a bit clever, thanks for these 👍  :) You should also offer again your logos on utopian, I choose my favorite

**Comment by linadesteem** [comment]
Thanks sir

**Comment by ggcarlosr** [comment]
The application for the coogger logo is still open?

**Comment by hakancelik96** [comment]
https://utopian.io/utopian-io/@hakancelik/need-web-design-advice-and-logo-for-coogger
