### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [coogger/coogger#35]
## Logo Proposal
![image](https://user-images.githubusercontent.com/35353768/39031770-bf012298-449c-11e8-8b52-c7d27f8d3fd8.png)
![image](https://user-images.githubusercontent.com/35353768/39031782-cd715a0a-449c-11e8-8011-dcc90d422533.png)
![jry](https://user-images.githubusercontent.com/35353768/39031901-afc635f6-449d-11e8-9d14-f18ca9f30c72.png)
![dffbdbdfbrdh](https://user-images.githubusercontent.com/35353768/39032130-c7331b86-449e-11e8-8f95-8ad4803587de.png)

**Comment by jbeguna04** [comment]
MY contribution: https://utopian.io/utopian-io/@jbeguna04/coogger-logo-proposal

**Comment by hakancelik96** [comment]
Thank you
