### ISSUE TITLE
My Logo Proposal For Cooger

### ISSUE THREAD

**Issue by dibon-github** [coogger/coogger#36]
Good Day, here is my logo proposal.

![full-color](https://user-images.githubusercontent.com/31919065/39035245-dfa83342-44ab-11e8-824f-8d10f89c2867.png)
![full-color](https://user-images.githubusercontent.com/31919065/39035264-f527b6e8-44ab-11e8-8f55-1b852cb3eab5.png)

**LOGO**

800PX
![800px](https://user-images.githubusercontent.com/31919065/39035405-70b35d80-44ac-11e8-9f57-3cdd886d60e4.png)
400PX
![400px](https://user-images.githubusercontent.com/31919065/39035409-73a06c54-44ac-11e8-8312-2ebafc75bd29.png)
200PX
![200px](https://user-images.githubusercontent.com/31919065/39035415-799f39c8-44ac-11e8-86d3-d209b9e2ccb6.png)

**ICONS**

48PX
![48px](https://user-images.githubusercontent.com/31919065/39035274-fef0dfba-44ab-11e8-8de8-9fcc3763defe.png)
36PX
![36px](https://user-images.githubusercontent.com/31919065/39035281-0745ad94-44ac-11e8-97c1-4d73d0dc55fe.png)
24PX
![24px](https://user-images.githubusercontent.com/31919065/39035285-0990c232-44ac-11e8-97de-040f145ded0a.png)
18PX
![18px](https://user-images.githubusercontent.com/31919065/39035287-0c5557d0-44ac-11e8-8a24-e5488e348f00.png)

**Comment by hakancelik96** [comment]
Thank you
