### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by nunojesus** [coogger/coogger#38]
Here is my Logo Proposal, You can download all the files here: https://drive.google.com/drive/folders/1ocIaXTvACw5QhzEBnVjgrltJ89YKmwQu?usp=sharing

In my proposal, I used the letter C of Coogger´s, tha was created through a structure composed of several lines connected to each other, representing network and share.

![logotype green](https://user-images.githubusercontent.com/34600369/39043429-4dc13abc-4485-11e8-946d-b1205ea4a57a.png)

![allfilesshis](https://user-images.githubusercontent.com/34600369/39043503-86129dc0-4485-11e8-8264-b5cb729a94d5.png)

**Comment by hakancelik96** [comment]
Thank you
