### ISSUE TITLE
Logo for coogger

### ISSUE THREAD

**Issue by mirzazulfan** [coogger/coogger#39]
Hi, here is my contribution [Link](https://utopian.io/utopian-io/@midun/logo-for-coogger)
![menu](https://user-images.githubusercontent.com/36124339/39055819-632013a6-44df-11e8-8964-6bffab726a85.png)

![mockup](https://user-images.githubusercontent.com/36124339/39055835-6b4fd8fe-44df-11e8-8199-91491a7c5c2c.png)

![variation 2](https://user-images.githubusercontent.com/36124339/39055846-730459e4-44df-11e8-8b2d-f2e668a9db10.png)

**Comment by hakancelik96** [comment]
Thank you
