### ISSUE TITLE
Logo Design Proposal for Coogger

### ISSUE THREAD

**Issue by anharismail** [coogger/coogger#40]
Hello Sir. I've created a logo for your task request. Hope you like it.

Full Presentation: https://utopian.io/utopian-io/@anharismail/logo-design-proposal-for-coogger-task-request

![cover](https://user-images.githubusercontent.com/37614260/39059095-d365cd9c-44e7-11e8-83df-e2b50157a38f.png)

**Comment by hakancelik96** [comment]
Thank you
