### ISSUE TITLE
Logo proposal for cooggger

### ISSUE THREAD

**Issue by jefz** [coogger/coogger#41]
Hello Sir, this is my proposal for the logo.
logotype 
![logotype2 1](https://user-images.githubusercontent.com/37773453/39060153-2c13e108-44f3-11e8-8c6c-9094b9a037a4.png)
![logotype2 2](https://user-images.githubusercontent.com/37773453/39060155-2e4dcb82-44f3-11e8-9e21-78c89448db79.png)
![logotype2 3](https://user-images.githubusercontent.com/37773453/39060157-301ab16e-44f3-11e8-848b-64fd94ffbf2a.png)

logo200x200
![logo1 200x200](https://user-images.githubusercontent.com/37773453/39060178-41559660-44f3-11e8-9ca8-6033203eafcb.png)
![logo2 200x200](https://user-images.githubusercontent.com/37773453/39060188-4778b838-44f3-11e8-8746-436bf3d07a9b.png)
![logo3 200x200](https://user-images.githubusercontent.com/37773453/39060190-499bbca0-44f3-11e8-9da6-c5afbf9b7873.png)

logo400x400
![logo1 400x400](https://user-images.githubusercontent.com/37773453/39060204-4ff031d0-44f3-11e8-8c21-fb98f65fdfd6.png)
![logo2 400x400](https://user-images.githubusercontent.com/37773453/39060207-52c75ffa-44f3-11e8-9c72-002b74be2c38.png)
![logo3 400x400](https://user-images.githubusercontent.com/37773453/39060208-560dfeee-44f3-11e8-8790-d534aeac857f.png)

logo800x800
![logo1 800x800](https://user-images.githubusercontent.com/37773453/39060220-5e0376f6-44f3-11e8-8d88-108d89bebbe8.png)
![logo2 800x800](https://user-images.githubusercontent.com/37773453/39060225-5fc88a30-44f3-11e8-83f9-70901d0ebe1e.png)
![logo3 800x800](https://user-images.githubusercontent.com/37773453/39060230-61a9f97e-44f3-11e8-8f1c-431a71a291ea.png)

icon sizes
18x18
![icon18x18 1](https://user-images.githubusercontent.com/37773453/39060247-6fa92c52-44f3-11e8-98e5-ec674d34b91c.png)
![icon18x18 2](https://user-images.githubusercontent.com/37773453/39060248-7031d264-44f3-11e8-96a1-d49b2e91ea34.png)
![icon18x18 3](https://user-images.githubusercontent.com/37773453/39060249-706e7584-44f3-11e8-83d5-f3b5e38100f9.png)

24x24
![icon24x24 1](https://user-images.githubusercontent.com/37773453/39060261-7ad4bc90-44f3-11e8-835e-ff5c12b27603.png)
![icon24x24 2](https://user-images.githubusercontent.com/37773453/39060262-7b158874-44f3-11e8-9911-db86d2201d90.png)
![icon24x24 3](https://user-images.githubusercontent.com/37773453/39060263-7b533b2e-44f3-11e8-9b3c-059932522941.png)

36x36
![icon36x36 1](https://user-images.githubusercontent.com/37773453/39060275-8151e840-44f3-11e8-9258-68cfe1341912.png)
![icon36x36 2](https://user-images.githubusercontent.com/37773453/39060276-81916d3a-44f3-11e8-919b-e7728ae40dd4.png)
![icon36x36 3](https://user-images.githubusercontent.com/37773453/39060277-81d2e9d6-44f3-11e8-8d42-3c3b1485e892.png)

48x48
![icon48x48 3](https://user-images.githubusercontent.com/37773453/39060286-877511c0-44f3-11e8-8b75-7ff046691d41.png)
![icon48x48 1](https://user-images.githubusercontent.com/37773453/39060287-87b172dc-44f3-11e8-9ce8-475647b7b13e.png)
![icon48x48 2](https://user-images.githubusercontent.com/37773453/39060288-87ef4ecc-44f3-11e8-9ba1-baeaa168067a.png)

**Comment by jefz** [comment]
sir, what do I do ? I posted 3 mins. late in utopian-io can it not consider sir? since I posted the issue here in time, because my net is so slow atm. pls sir help me

**Comment by hakancelik96** [comment]
Thank you
