### ISSUE TITLE
More minimalist and modern header

### ISSUE THREAD

**Issue by Yutyo** [coogger/coogger#91]
I think a header likes this would be awesome at coogger.com: 
![coogersite](https://user-images.githubusercontent.com/40173707/61253984-af8b6c00-a76b-11e9-9a7e-9965b24256ca.png)

**Comment by Yutyo** [comment]
Also, as you see in image, it looks better when remarkable topics and open issues sections are floated to left and right.

**Comment by hakancelik96** [comment]
That is correct, I working on it.
