### ISSUE TITLE
Make blacklist for bad words/ Küfürler için karaliste yap

### ISSUE THREAD

**Issue by Yutyo** [coogger/coogger#95]
I think a blacklist for bad words is needed as we would face bad words in the future. 

Here is a pre-made bad words list for Turkish: 
https://notabug.org/ooguz/turkce-kufur-karaliste/src/master/karaliste.txt

**Comment by hakancelik96** [comment]
I don't think this feature should be added, the report feature already exists, in these cases, the content is reported by users who uncomfortable then If the content does not the rules comply, the content is removed.
